### ISSUE TITLE
Milestone - week 1

### ISSUE THREAD

**Issue by JMoortensen** [fauzan-arif/ds-capstone#6]
# Milestones - week 1
Hi team(s), here we can add and track our weekly milestones. Please link the issue corresponding to the milestone.

## Team Telegram Scrapper
- [ ] **Task 1 (insert link to issue)**
  - [ ] Subtask 1.1
  - [ ] Subtask 1.2
- [ ] **Task 2**
  - [ ] Subtask 2.1
  - [ ] Subtask 2.2
- [ ] **Task 3**
  - [ ] Subtask 3.1
  - [ ] Subtask 3.2

## DataDrivenDollar
- [ ] **Dataset (insert link to issue here)**
  - [ ]  [Web Scrapper](https://github.com/max-power/ds-capstone/issues/7#issue-2037794214)
  - [ ] Subtask 1.2
- [ ] **Full scope of project**
  - [ ] Subtask 2.1
  - [ ] Subtask 2.2
- [ ] **First idea of ML models to use (potential test)**
  - [ ] Subtask 3.1
  - [ ] Subtask 3.2
